### ISSUE TITLE
Modifier not working on 5.0.1 & Ember 3.25.1

### ISSUE THREAD

**Issue by chasegiunta** [zeppelin/ember-click-outside#253]
Can't tell you why, but trying this addon out, and I was unable to get the modifier to work:

`{{on-click-outside this.handleClickOutside}}` (per readme, did nothing).

However, downgrading to 4.0 with `{{on-click-outside (action this.handleClickOutside)}}` seemed to work like a charm.

**Comment by knownasilya** [comment]
I got an error like `ember-click-outside needs to depend on ember-auto-import in order to use ember-modifier`

**Comment by jonr-luma** [comment]
> I got an error like `ember-click-outside needs to depend on ember-auto-import in order to use ember-modifier`

I am also seeing the same issue

**Comment by st-h** [comment]
> I got an error like `ember-click-outside needs to depend on ember-auto-import in order to use ember-modifier`

Not sure about the initial issue, but regarding the auto-import issue, it seems that current ember-modifier versions require auto-import v2. This addon still uses the v1 auto-import: https://github.com/ember-modifier/ember-modifier

**Comment by zeppelin** [comment]
Hey everyone 👋 Can't believe this has been sitting here since last November 🤦

Anyway, I've released `6.0.0-beta.1`, which is a v2 addon but should work just fine in 3.25, it only requires `ember-auto-import@2` as @st-h suggested. If you haven't been importing private stuff from the addon this should not be a breaking change per se, but as the tag suggests, it's better be sure before I cut `6.0.0`.

Let me know if you run into issues, so that I can fix them for `v6`

**Comment by knownasilya** [comment]
Worked here

**Comment by st-h** [comment]
looking good here as well 👍

**Comment by zeppelin** [comment]
[Released `6.0.0`](https://github.com/zeppelin/ember-click-outside/releases/tag/v6.0.0), closing this one. Thanks everyone for being patient! 🙏
